topnav_title: CCG
homepage_title: Cognitive Computation Group
site_title: CogComp
company_name: CogComp
footer_image_location: ccg.png
# variables

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
