theme: jekyll-theme-minimal
title: CogComp
description: [The Cognitive Computation Group is led by Prof Dan Roth in the Department of Computer and Information Science at University of Pennsylvania.]
logo: ccg.png
