theme: jekyll-theme-minimal
title: CogComp
description: [The Cognitive Computation Group is led by Prof Dan Roth, Department of Computer and Information Science, University of Pennsylvania.]
logo: ccg.png
